<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DIL-TOS-180706" name="testcases.Simulator_TC" tests="46" failures="3" timestamp="07 mar 2019 17:04:01 GMT" time="656.988" errors="0">
  <testcase name="runSimulation" time="12.069" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="17.340" classname="testcases.Simulator_TC">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at testcases.Simulator_TC.runSimulation(Simulator_TC.java:69)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runSimulation -->
  <testcase name="runSimulation" time="14.767" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="15.428" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="12.859" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="11.297" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="13.285" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="11.693" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="12.699" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="11.536" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="14.956" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="13.427" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="15.656" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="17.771" classname="testcases.Simulator_TC">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at testcases.Simulator_TC.runSimulation(Simulator_TC.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runSimulation -->
  <testcase name="runSimulation" time="11.995" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="14.504" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="13.966" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="11.928" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="14.017" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="16.942" classname="testcases.Simulator_TC">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at testcases.Simulator_TC.runSimulation(Simulator_TC.java:69)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runSimulation -->
  <testcase name="runSimulation" time="13.864" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="12.080" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="16.313" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="11.694" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="16.509" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="17.373" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="11.698" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="14.403" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="13.339" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="12.769" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="28.816" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="12.080" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="11.589" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="14.048" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="11.698" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="11.443" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="15.859" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="14.835" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="14.764" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="11.420" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="20.778" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="15.213" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="14.807" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="12.794" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="15.582" classname="testcases.Simulator_TC"/>
  <testcase name="runSimulation" time="13.085" classname="testcases.Simulator_TC"/>
</testsuite> <!-- testcases.Simulator_TC -->
